#!/bin/bash
#important
#good color demo
#source /home/steff007/pys/colors
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)
#printf "%s\n" "${RED}File does not exist"

#!/bin/bash
#important
#good color demo
#source /home/steff007/pys/colors
#if [[ -e $1 ]] 
#then
  #printf "%s\n" "${BLUE}File exists." 
#else
  #printf "%s\n" "${RED}File does not exist"
#fi

